name: Simple variables and secrets example

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print variables and secret
        run: |
          echo "User running this workflow: $GITHUB_USER"
          echo "Custom message: $MY_MESSAGE"
          echo "Secret says: $MY_SECRET_VALUE"
        env:
          GITHUB_USER: ${{ github.actor }}
          MY_MESSAGE:  "workflow variable message"
          MY_SECRET_VALUE: ${{ secrets.MY_SECRET }}
