name: Pass a value between jobs

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      message: ${{ steps.set_value.outputs.out }}

    steps:
      - name: Set output value
        id: set_value
        run: echo "out=Hello_from_job1" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Print the value passed from job1
        run: echo "Job1 said: ${{ needs.job1.outputs.message }}"
